spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/authtestdb
    username: pguser
    password: pgpass
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
#        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          lob:
            non_contextual_creation: true
        format-sql: true
        show-sql: true
    open-in-view: false
