spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:authtestdb;DATABASE_TO_UPPER=false;IGNORECASE=TRUE;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
#        dialect: org.hibernate.dialect.H2Dialect
        format-sql: true
        show-sql: true
    open-in-view: false
  h2:
    console:
      enabled: true